version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: smartnotes-db
    environment:
      POSTGRES_DB: smartnotes
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: smartnotes-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: smartnotes-kafka
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  prometheus:
    image: prom/prometheus:latest
    container_name: smartnotes-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on: []

  grafana:
    image: grafana/grafana:latest
    container_name: smartnotes-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on: [prometheus, loki]

  loki:
    image: grafana/loki:latest
    container_name: smartnotes-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: smartnotes-promtail
    volumes:
      - ./logs:/logs                                    # your Spring logs folder
      - ./monitoring/promtail.yml:/etc/promtail/config.yml
    depends_on: [loki]

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: smartnotes-zipkin
    ports:
      - "9411:9411"

volumes:
  postgres_data:
  grafana_data: