spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartnotes
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update       # auto-creates tables from your entities
    show-sql: true           # prints SQL in console — useful while learning
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: smartnotes-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  # ← keep this
      properties:
        "[spring.json.trusted.packages]": "*"
        "[spring.json.value.default.type]": "com.smartnotes.smartnotes_backend.kafka.NoteEvent"
server:
  port: 8080

# Add at the bottom of application.yml
ollama:
  base-url: http://localhost:11434
  model: gemma4